version: "3.8"

services:
  llm:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama   # сохраняем модели и настройки
    ports:
      - "11434:11434"              # REST API порт
    command: ["serve"]              # запускаем Ollama сервер
    networks:
      - net


  pull-model:
    image: genai-stack/pull-model:latest
    build:
      context: .
      dockerfile: pull_model.Dockerfile
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://llm:11434   # обращаемся к сервису по имени контейнера
      - LLM=${LLM}
    networks:
      - net
    depends_on:
      - llm
    tty: true

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - OLLAMA_BASE_URL=http://llm:11434
      - LLM=${LLM}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    networks:
      - net
    depends_on:
      - pull-model
    ports:
      - "8504:8504"

  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: telegram_bot.Dockerfile
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://llm:11434
      - LLM=${LLM}
      - CHANNEL_ID=${CHANNEL_ID}
      - ADMIN_ID=${ADMIN_ID}
      - TOKEN=${TOKEN}
    networks:
      - net
    ports:
      - "8506:8506"
    depends_on:
      - pull-model

volumes:
  ollama_data:

networks:
  net:
    name: net
    driver: bridge
